name: Scan

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "23 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: scan-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: uinaf/.github/.github/workflows/scan.yml@main
